system_name: "Overcalling"
priority: 60
description: "Overcalling"

trigger:
  conditions:
    seat_role: "overcaller"
    
nodes:
  - bid: "X"
    type: "Natural"
    meaning: "Showing 16+ points"
    constraints:
      hcp: ">=16"
    next_state: "overcalled"
  
  - dynamic_bid:
      bid_type: "length_bid"
    type: "overcall"
    meaning: "length in named suit"
    constraints:
      shape:
        any: ">=6"
    next_state: "overcall"
  

