system_name: "Responses to 2NT"
priority: 60
description: "Replies to 2NT"

trigger:
  conditions:
    current_state: "2nt_response"
    seat_role: "responder"

nodes:
  - bid: "3D"
    type: "Convention"
    meaning: "Transfer to hearts"
    constraints:
      shape:
        hearts: ">=5"
    next_state: "transfer_response"

  - bid: "3H"
    type: "Convention"
    meaning: "Transfer to spades"
    constraints:
      shape:
        spades: ">=5"
    next_state: "transfer_response"

  - bid: "3C"
    type: "Convention"
    meaning: "Stayman: Asking for 4-card major"
    constraints:
      hcp: ">= 4"
      any_of:
        - shape: { hearts: ">= 4" }
        - shape: { spades: ">= 4" }
    next_state: "2nt_stayman_response"

  - bid: "3NT"
    type: "Convention"
    meaning: "Stayman: Asking for 4-card major"
    constraints:
      hcp: "4-10" 
    next_state: "natural_response"
  
