system_name: "Overcalling"
priority: 60
description: "Overcalling"

trigger:
  conditions:
    seat_role: "overcaller"
    any_of:
      - history_pattern: ["Pass*","1NT"]
      - history_pattern: ["Pass*","1NT","Pass","Pass"]
    
nodes:
  - bid: "X"
    type: "Natural"
    meaning: "Showing 16+ points"
    constraints:
      hcp: ">=16"
    next_state: "overcall"


