system_name: "Opener Rebids to Stayman"
priority: 60
description: "Replies to 2C Stayman"

trigger:
  conditions:
    current_state: "stayman"
    seat_role: "opener"
    
nodes:
  - bid: "2H"
    type: "Natural"
    meaning: "Showing 4 Hearts (may also have Spades)"
    constraints:
      shape:
        hearts: ">= 4"
    next_state: "stayman"

  - bid: "2S"
    type: "Natural"
    meaning: "Showing 4 Spades (Denies 4 Hearts)"
    constraints:
      shape:
        spades: ">= 4"
    next_state: "stayman"

  # Default: No Majors
  - bid: "2D"
    type: "Artificial"
    meaning: "No 4-card major"
    constraints:
      # Explicitly ensure we DON'T have majors to avoid ambiguity logic issues
      shape:
        hearts: "<= 3"
        spades: "<= 3"
    next_state: "stayman"