system_name: "Acol - Basic Openings"
priority: 10 # Low priority. Conventions (like Preempts) will override this.
description: "Traditional Acol with Weak 1NT and 4-card Majors"

# Trigger for an opening bid (0 passes, or passes only)
trigger:
  conditions:
    history_pattern: ["Pass*"] # Regex: Matches empty, "Pass", "Pass, Pass", etc.
    current_state: "opening"

nodes:
  - bid: "1H"
    type: "Natural"
    meaning: "12-19 HCP, 4+ Hearts" # Acol typically opens 4-card majors
    constraints:
      hcp: "12-19"
      any_of:
      - shape:
          hearts: ">= 5"
    next_state: "natural"
    
  - bid: "1S"
    type: "Natural"
    meaning: "12-19 HCP, 4+ Spades" 
    constraints:
      hcp: "12-19"
      shape:
        spades: ">= 5"
    next_state: "natural"
    
  - bid: "1C"
    type: "Natural"
    meaning: "12-19 HCP, 4+ Clubs" 
    constraints:
      hcp: "12-19"
      shape:
        clubs: ">= 5"
    next_state: "natural"

  - bid: "1D"
    type: "Natural"
    meaning: "12-19 HCP, 4+ Diamonds"
    constraints:
      hcp: "12-19"
      shape:
        diamonds: ">= 5"
    next_state: "natural"
  
  - bid: "Pass"
    type: "Natural"
    meaning: "Pass"
    constraints:
      hcp: "<=12"
      shape:
        any: "<=6"
    next_state: "opening"

