system_name: "Acol - 2 level (3 weak 2s)"
priority: 20
description: "2 Level - Traditional Acol with Weak 1NT and 4-card Majors"

# Trigger for an opening bid (0 passes, or passes only)
trigger:
  conditions:
    history_pattern: ["Pass*"] # Regex: Matches empty, "Pass", "Pass, Pass", etc.

nodes:
  - bid: "2NT"
    type: "Natural"
    meaning: "20-22 HCP, Balanced"
    constraints:
      hcp: "20-22"
      shape: "balanced"
    next_state: "2nt_response"
    
  - bid: "2S"
    type: "Weak"
    meaning: "Weak hand, 6 cards in spades"
    constraints:
      shape:
        spades: ">=6"
      hcp: 6-10
    next_state: "natural_response"
    
  - bid: "2H"
    type: "Weak"
    meaning: "Weak hand, 6 cards in hearts"
    constraints:
      shape:
        hearts: ">=6"
      hcp: 6-10
    next_state: "natural_response"
    
  - bid: "2D"
    type: "Weak"
    meaning: "Weak hand, 6 cards in diamonds"
    constraints:
      shape:
        diamonds: ">=6"
      hcp: 6-10
    next_state: "natural_response"
    
  - bid: "2C"
    type: "Artificial"
    meaning: "Very strong hand"
    constraints:
      any_of:
        - hcp: ">=23"
          shape: "balanced"
        - losers: "<=3"
    next_state: "strong"

#  - dynamic_bid: 
#      bid_type: "length_bid"
#      type: "weak"
#      forbidden: "2c"
#    type: "Natural"
#    meaning: "6-10 HCP, 6+ cards in suit" # Acol typically opens 4-card majors
#    constraints:
#      hcp: "6-10"
#      shape:
#        any: ">= 6"
#    next_state: "natural"

