system_name: "Acol - 2 level (3 weak 2s)"
priority: 21
description: "2 Level - Traditional Acol with Weak 1NT and 4-card Majors"

# Trigger for an opening bid (0 passes, or passes only)
trigger:
  conditions:
    history_pattern: ["Pass*"] # Regex: Matches empty, "Pass", "Pass, Pass", etc.

nodes:
  - bid: "3S"
    type: "Weak"
    meaning: "Weak hand, 6 cards in spades"
    constraints:
      shape:
        spades: "=7"
      hcp: 6-10
    next_state: "natural_response"
    
  - bid: "3H"
    type: "Weak"
    meaning: "Weak hand, 6 cards in hearts"
    constraints:
      shape:
        hearts: "=7"
      hcp: 6-10
    next_state: "natural_response"
    
  - bid: "3D"
    type: "Weak"
    meaning: "Weak hand, 6 cards in diamonds"
    constraints:
      shape:
        diamonds: "=7"
      hcp: 6-10
    next_state: "natural_response"
    
  - bid: "3C"
    type: "Weak"
    meaning: "Weak hand, 6 cards in diamonds"
    constraints:
      shape:
        clubs: "=7"
      hcp: 6-10
    next_state: "natural_response"

#  - dynamic_bid: 
#      bid_type: "length_bid"
#      type: "weak"
#      forbidden: "2c"
#    type: "Natural"
#    meaning: "6-10 HCP, 6+ cards in suit" # Acol typically opens 4-card majors
#    constraints:
#      hcp: "6-10"
#      shape:
#        any: ">= 6"
#    next_state: "natural"

