system_name: "Opener Rebids to 2NT Stayman"
priority: 100
description: "Replies to 3C Stayman"

trigger:
  conditions:
    current_state: "2nt_stayman_response"
    seat_role: "opener"

nodes:
  - bid: "3H"
    type: "Natural"
    meaning: "Showing 4 Hearts (may also have Spades)"
    constraints:
      shape:
        hearts: ">= 4"
    next_state: "natural_response"

  - bid: "3S"
    type: "Natural"
    meaning: "Showing 4 Spades (Denies 4 Hearts)"
    constraints:
      shape:
        spades: ">= 4"
    next_state: "natural_response"

  - bid: "3D"
    type: "Artificial"
    meaning: "No 4-card major"
    constraints:
      shape:
        hearts: "<= 3"
        spades: "<= 3"
    next_state: "natural_response"